# Generated by Django 4.2 on 2023-05-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время рассылки')),
                ('frequency',
                 models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1,
                                  verbose_name='Периодичность')),
                ('status',
                 models.CharField(choices=[('F', 'Finished'), ('C', 'Created'), ('S', 'Started')], max_length=1,
                                  verbose_name='Статус рассылки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters',
                                             to='app_newsletter.client', verbose_name='Клиент')),
                ('messages', models.ManyToManyField(related_name='newsletters', to='app_newsletter.message',
                                                    verbose_name='Сообщения')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'newsletters',
            },
        ),
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('status',
                 models.CharField(choices=[('S', 'Success'), ('F', 'Failure')], max_length=1, verbose_name='Статус')),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('newsletter',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_log',
                                   to='app_newsletter.newsletter', verbose_name='Рассылка')),
            ],
        ),
    ]
