# Generated by Django 4.2 on 2023-05-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_newsletter', '0003_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')],
                                   max_length=1, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('F', 'Завершена'), ('C', 'Создана'), ('S', 'Запущена')], max_length=1,
                                   verbose_name='Статус рассылки'),
        ),
    ]
