# Generated by Django 4.2 on 2023-05-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_newsletter', '0004_alter_newsletter_frequency_alter_newsletter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='client',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(related_name='newsletters', to='app_newsletter.client', verbose_name='Клиенты'),
        ),
    ]
