# Generated by Django 4.2 on 2023-05-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_newsletter', '0005_remove_newsletter_client_newsletter_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
    ]
