# Generated by Django 4.2 on 2023-05-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_newsletter', '0007_newsletter_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterlog',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='newsletterlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app_newsletter.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='newsletterlog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app_newsletter.message', verbose_name='Сообщение'),
        ),
    ]
