# Generated by Django 4.2 on 2023-05-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_newsletter', '0008_remove_newsletterlog_newsletter_newsletterlog_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterlog',
            options={'verbose_name': 'Лог отправки письма', 'verbose_name_plural': 'Логи отправок писем'},
        ),
        migrations.AddField(
            model_name='newsletterlog',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app_newsletter.newsletter', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='app_newsletter.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='newsletterlog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='app_newsletter.message', verbose_name='Сообщение'),
        ),
    ]
