# Generated by Django 4.2 on 2023-05-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_newsletter', '0009_alter_newsletterlog_options_newsletterlog_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlog',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_newsletter.newsletter', verbose_name='Рассылка'),
        ),
    ]
