# Generated by Django 4.2 on 2023-05-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_newsletter', '0011_newsletter_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='finish_time',
            field=models.DateTimeField(verbose_name='Дата и время завершения рассылки'),
        ),
    ]
