# Generated by Django 4.2 on 2023-05-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_catalog', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Индекс')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта')),
                ('tin', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Контакт компании',
                'verbose_name_plural': 'Контакты компании',
                'db_table': 'company_contact',
            },
        ),
    ]
