# Generated by Django 4.2 on 2023-05-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_catalog', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-03 00:00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
